# Generated by Django 4.1.4 on 2022-12-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmlink',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
